Us12 us21 us25 us32 ur13 create session flow
SpotifyMasterProject/spotify-xai pull request #100
Opened 2024-08-18 17:37 UTC by danielamormocea

2024-08-19 11:49 UTC, maettuu requested changes
open questions for BE, also implementation of spotipy.

2024-08-19 11:49 UTC, maettuu commented on server/app/controller.py
> +async def lifespan(_: FastAPI):
I moved this to the service, I think it isn't required to be in the controller. What is your use case? :)

2024-08-19 11:49 UTC, maettuu commented on server/app/models/__init__.py
why did you add a __init__ file? I think models can stay directory, do you need it to be a package?

2024-08-19 11:49 UTC, maettuu commented on server/app/models/session.py
> -    guests: Optional[List[str]] = []
this should remain optional, since when a session starts there are no guests yet :)

2024-08-19 11:49 UTC, maettuu commented on server/app/models/session.py
> +    playlist: List[Song] = []
I would also use the Optional argument here, because there are no songs in the beginning right?

2024-08-19 11:49 UTC, maettuu commented on server/app/models/session.py
> +    is_running: bool = False
what do we need this bool for?

2024-08-19 11:49 UTC, maettuu commented on server/app/service.py
> +    async def get_sessions(self, user_id: str) -> List[Session]:
why do we need this functionality? are we enabling a host to start several sessions?

2024-08-19 12:07 UTC, maettuu commented on server/app/controller.py
> +@app.get("/sessions/join/{invite_token}", status_code=status.HTTP_200_OK, response_model=AnonymousSession)
what is this endpoint used for?

2024-08-19 12:09 UTC, maettuu commented on server/app/controller.py
> +    return songsDataset.get_matching_songs(pattern)
we could probably merge this somehow with the service no? instead of having a song_dataset.py - once we figure out how to connect a redis with it, we can also use the repo respectively

2024-08-19 12:10 UTC, maettuu commented on server/app/service.py
> +    def exchange_code_for_token(auth_code: str) -> str:
this should be a @staticmethod I think

2024-08-19 18:17 UTC, danielamormocea commented on server/app/controller.py
> +async def lifespan(_: FastAPI):
I needed to use the session object in the lifespan function, for mocking some entries in the repo (creating some users and some sessions). I thought that we may want to keep it here, in case we want to do that in the future, under some debug flag. I think by keeping it here we have access to all the global objects in the server, so it may be easier to interact with them.

2024-08-19 18:19 UTC, danielamormocea commented on server/app/models/__init__.py
I have some interdependency between the models and having an init makes it easier to import the files. Do you think there are downsides of having it as a package?

2024-08-19 18:21 UTC, danielamormocea commented on server/app/models/session.py
> -    guests: Optional[List[str]] = []
Yep, that's why we are having an empty list. By default it would be empty. The current flow works (tested the E2E flow, see also the screencasts: creating a session, getting sessions). I think we discussed this also briefly in your PR. For lists, we could just use the empty list as the initial value.

2024-08-19 18:22 UTC, danielamormocea commented on server/app/models/session.py
> +    playlist: List[Song] = []
Same argument as above, but in this case we also do have songs initially (the host adds 3 songs before creating the session).

2024-08-19 18:23 UTC, danielamormocea commented on server/app/models/session.py
> +    is_running: bool = False
To check if a session is still running or not. This would impact the UI (e.g, we can add songs to a running session, but not to one that ended).

2024-08-19 18:23 UTC, danielamormocea commented on server/app/service.py
> +    def exchange_code_for_token(auth_code: str) -> str:
Yep, forgot to remove the comment.

2024-08-19 18:25 UTC, danielamormocea commented on server/app/service.py
> +    async def get_sessions(self, user_id: str) -> List[Session]:
No, it's so we can get all the sessions for a host (the running one and the old ones that finished). We call this method when we enter the home page (and at every refresh), so we can instantiate the page with the current and old sessions. Without it, we won't be able to list the session history for a host.

2024-08-19 19:28 UTC, danielamormocea commented on server/app/controller.py
> +@app.get("/sessions/join/{invite_token}", status_code=status.HTTP_200_OK, response_model=AnonymousSession)
To get metadata about a session. Mostly the host's username so that we can show it in the UI, prior to joining. You can also look in the sessionService in the client to see the calls.

2024-08-19 19:30 UTC, danielamormocea commented on server/app/controller.py
> +    return songsDataset.get_matching_songs(pattern)
I think it's useful to have this separate for now. Having it in the service adds a bit more abstraction and for now we don't actually need it. Maybe in the future it makes sense? WDYT?

2024-08-20 13:55 UTC, jemaie commented on server/app/controller.py
i have looked at this file trying to understand what is going on for a while. this file (besides the propagation to other files) contains changes that we have not discussed. they also do not appear in any documentation we have set up to clarify what we are doing. as you have mentioned, you like fast development, but you must see that no documentation to your changes brings me a significant increase in effort.
as we have discussed previously, more communication is needed.

besides this, i don't like the flow changes and the misuse/abuse of endpoints i have seen within this file (referencing the Endpoint file once more. how should the rest of us know what they are good foor etc.?). let's discuss some details in the next meeting.

2024-08-20 17:21 UTC, danielamormocea commented on server/app/controller.py
Adding documentation is something that I am defintely willing to do (I am adding comments in the code where I see that the code is not self-explanatory). If you think there is a lack of documentation, you could just nicely point this out and I could both: add comments here explaining what functions do (if it's not clear) and add the endpoints to the sheet. My impression was that these are minimal changes and do not require a lot of extra documentation.

I also do not understand what you mean by misuse / abuse of endpoints. At the time I implemented these changes both the endpoints in this file as well as the ones in the sheet, were not sufficient for the login flow. I just added some to fulfill the user stories and I used them (so I do not get what misusage you see).

In my mind, you could have nicely pointed out that we should add documentation about this, as well as briefly ask about what each endpoint does. But, as a sidenote, this file is not meant to be looked at in a standalone manner. You should also check the FE, and see how I used them, as I think that would make the flow more clear and understandable.

Regarding missing documentation, I would also like to point out that the /ws/ as well as the /leave endpoint are missing from the sheet and are also not documented in the code, so there is a lack of consistency here during reviews. If we would like that every endpoint has a matching entry in the sheet, then we should require this during every code review.

2024-08-22 07:57 UTC, maettuu requested changes
left comments on what I would love to keep in the BE :) will add my endpoints after and then the FE needs adapting. If you want I'd love to let you do that, because I don't wanna deal with it haha - but lmk if I should do it!

2024-08-22 07:57 UTC, maettuu commented on server/app/controller.py
> +@app.get("/songs/{pattern}", status_code=status.HTTP_200_OK, response_model=list[Song])
keep this endpoint!

2024-08-22 07:57 UTC, maettuu commented on server/app/controller.py
> +async def get_session(invite_token: str) -> Session:
keep this endpoint, but return a full session object

2024-08-22 07:57 UTC, maettuu commented on server/app/recommender/songs_dataset.py
keep all changes in this file! (I myself have a song model, so you can leave the import :D)

2024-08-22 07:57 UTC, maettuu commented on server/app/recommender/tests/songs_dataset_test.py
keep these changes

2024-08-22 07:57 UTC, maettuu commented on server/app/service.py
> +        session.invite_link = f'http://{os.getenv("LOCAL_IP_ADDRESS")}:8080/sessions/join/{session.invite_token}'
keep this change!

2024-08-22 07:57 UTC, maettuu commented on server/app/models/user.py
> +    sessions: List[str] = []
keep this change! I like it

2024-08-22 07:57 UTC, maettuu commented on server/app/service.py
> +        user = User.model_validate_json(await self.repo.get_user_by_id(host_id))
keep this :) might refactor it a bit to have the user already in the controller, but the logic to add the session to the user's session list is nice!

2024-08-22 07:57 UTC, maettuu commented on server/app/service.py
> +    async def get_session_by_id(self, session_id: str) -> Session:
keep this :)

2024-08-26 10:05 UTC, maettuu approved these changes

2024-08-26 10:05 UTC, merged