Reply #100 BE Changes
SpotifyMasterProject/spotify-xai pull request #107
Opened 2024-08-21 09:40 UTC by maettuu

Here's the implementation of the flow we agreed upon :)

1. host creates new session
2. the invite link is generated now using session_id directly
3. when scanning qr_code session details can be requested using the session_id
4. all information can be displayed and guest enters username with which the request to join is made
5. the endpoint to join a session is POST "/sessions/{session_id}/guests"

2024-08-21 10:53 UTC, danielamormocea commented
Why do we need to have all session details for users that are not logged in?

2024-08-21 11:01 UTC, danielamormocea commented on server/app/controller.py
> +async def get_songs(user_id: Annotated[str, Depends(service.verify_token)], pattern: str) -> list[Song]:
I'm confused - I put them already in my PR - why did you copy them?

2024-08-21 11:05 UTC, danielamormocea requested changes
It seems that a lot of the functionalities here were added 3 days ago (in PR#100), tackled in my PR - so I'm confused why these are duplicates.  This feels very wrong.

2024-08-27 12:47 UTC, jemaie commented on server/app/models/song.py
why are all fields except artist(_id)s optional? lets make these also optional or remove optional from the others where not necessary

2024-08-29 14:43 UTC, maettuu commented on server/app/models/song.py
because dana showed us when initializing lists, the optional parameter can be removed, is works perfectly fine :)

2024-08-29 19:00 UTC, merged