US15 session visualization (base design)
SpotifyMasterProject/spotify-xai pull request #71
Opened 2024-08-06 13:44 UTC by saeie07

Created the base design
- Front page (Landing page with Start Button (not activated yet))
- Home (Session Design - basic buildup)
- Petal and Flower Component
- Navigation Component (will be deleted in future)
- Content from original landinpage is now within about

2024-08-06 17:23 UTC, danielamormocea commented on client/src/App.vue
>  import { RouterLink, RouterView } from 'vue-router'
`RouterLink` is not used.

2024-08-06 17:25 UTC, danielamormocea commented on client/src/assets/base.css
> +  --Font-color: #FFFFFF;
Should we keep them all lower cased, for consistency?

2024-08-06 17:36 UTC, danielamormocea commented on client/src/components/Petal.vue
> +      return `#${(0x1000000 + (R < 255 ? R < 1 ? 0 : R : 255) * 0x10000 + (G < 255 ? G < 1 ? 0 : G : 255) * 0x100 + (B < 255 ? B < 1 ? 0 : B : 255)).toString(16).slice(1)}`;
This is very hard to read. Maybe add some comments to explain what this is doing?

2024-08-06 17:36 UTC, danielamormocea commented on client/src/components/Petal.vue
> +    lightenColor(color, percent) {
This is very hard to read. Maybe add some comments to explain what this is doing?

2024-08-06 17:38 UTC, danielamormocea commented on client/src/components/StartBlendButton.vue
> +    width: calc(40px + (200 * (100vh - 100px) / 350));
Is this necessary? Seems overly complex.

2024-08-06 17:42 UTC, danielamormocea commented on client/src/views/LandingView.vue
> +      <start-blend-button />
Shouldn't this page have the login buttons? I'm not sure I understand why they are in the AboutView?

2024-08-06 17:44 UTC, danielamormocea commented on client/src/components/Navigation.vue
> +  <nav class="navigation-bar">
Do we actually need a Navigation component? It seems to be that the only 2 visible pages are Landing  and Home. Websocket seems for internal testing, and not sure what About is for (we could also just have a button for that if necessary).

2024-08-06 17:46 UTC, danielamormocea commented on client/src/assets/main.css
> +.type1 {
Maybe a more verbose name makes more sense? Maybe: "single-layout" and "three-part-layout"?

2024-08-06 17:48 UTC, danielamormocea commented on client/src/router/index.ts
> -      meta: { requiresAuth: true }
Why do we remove the need for authentication here? Shouldn't only logged in users have access?

2024-08-06 17:49 UTC, danielamormocea requested changes
Thanks a lot for this! Left a few comments, let me know what you think.

2024-08-07 07:27 UTC, saeie07 commented on client/src/App.vue
>  import { RouterLink, RouterView } from 'vue-router'
adapted

2024-08-07 07:29 UTC, saeie07 commented on client/src/assets/base.css
> +  --Font-color: #FFFFFF;
should all be upper case. I haven't seen any lower case. or where do you mean?

2024-08-07 07:30 UTC, saeie07 commented on client/src/components/Petal.vue
> +    lightenColor(color, percent) {
will keep as is now because im still working on it and it might change.

2024-08-07 07:31 UTC, saeie07 commented on client/src/components/StartBlendButton.vue
> +    width: calc(40px + (200 * (100vh - 100px) / 350));
yes, need it for a responsive display. otherwise the size does not change properly. plus still needs to be fine-tuned, so would leave it for now.

2024-08-07 07:33 UTC, saeie07 commented on client/src/views/LandingView.vue
> +      <start-blend-button />
See description of PR
- Content from original landinpage is now within about

login will be added once were ready / it makes sense - would just cause a lot of logins to work on design - so I would add this at the end, now we can easily jump back and forth to check the layout

2024-08-07 07:33 UTC, saeie07 commented on client/src/components/Navigation.vue
> +  <nav class="navigation-bar">
See description of PR
- Navigation Component (will be deleted in future)

2024-08-07 07:34 UTC, saeie07 commented on client/src/assets/main.css
> +.type1 {
would keep for now, since the css code is also named type 1 and type 2.

2024-08-07 07:34 UTC, saeie07 commented on client/src/router/index.ts
> -      meta: { requiresAuth: true }
yes, but need to be able to get into the Home Screen for design purpose without having to authenticate right now.

2024-08-07 07:51 UTC, saeie07 commented
Thanks a lot for the review. I have made a few changes to the code based on review. Most I have however, left for now, since they will be addressed in the future (navigation, authentication, etc).

2024-08-07 08:33 UTC, danielamormocea commented on client/src/assets/base.css
> +  --Font-color: #FFFFFF;
--Font-color - exactly at the line I commented

2024-08-07 08:36 UTC, danielamormocea commented on client/src/components/Navigation.vue
> +  <nav class="navigation-bar">
Then we should not add dead code to the main, I would suggest to remove it

2024-08-07 08:38 UTC, danielamormocea commented on client/src/components/Flower.vue
> +export default {
@saeie07 this has not been addressed yet - It shouldn't be merged like this, without having consistency throughout the code

2024-08-07 08:43 UTC, danielamormocea requested changes
I still think we shouldn't add the code as is to main, there are still changes that could be adapted now, or else I fear they may be forgotten or left on somebody else to fix

2024-08-07 08:46 UTC, danielamormocea commented on client/src/router/index.ts
> -      meta: { requiresAuth: true }
Then please do that locally - no need to push this to main

2024-08-07 08:56 UTC, maettuu commented on client/src/router/index.ts
> -      meta: { requiresAuth: true }
would comment it out for now :) but would not remove it

2024-08-07 08:57 UTC, maettuu commented on client/src/components/StartBlendButton.vue
> +    width: calc(40px + (200 * (100vh - 100px) / 350));
CSS is complex ^^ this is totally normal for responsiveness and height calculations

2024-08-07 09:01 UTC, maettuu commented on client/src/assets/main.css
> +.type1 {
is this something we have to choose between? so either type 1 or 2?

2024-08-07 09:17 UTC, danielamormocea commented on client/src/components/Petal.vue
> +    lightenColor(color, percent) {
I did not request a change here, just a comment would be nice for explainability :) thanks

2024-08-07 10:06 UTC, saeie07 commented on client/src/assets/base.css
> +  --Font-color: #FFFFFF;
adapted

2024-08-07 10:07 UTC, saeie07 commented on client/src/components/Flower.vue
> +export default {
adapted

2024-08-07 10:11 UTC, saeie07 commented on client/src/components/StartBlendButton.vue
> +    width: calc(40px + (200 * (100vh - 100px) / 350));
would leave as is

2024-08-07 10:12 UTC, saeie07 commented on client/src/components/Petal.vue
> +    lightenColor(color, percent) {
again, this was part of the PR in the current state and works well for this state. However, it will be changed. I am working on it today and will be different either way, I will make sure to add comments within the new PR, so I would not add additional work as of now because it will change within the next few hours.

2024-08-07 10:15 UTC, saeie07 commented on client/src/router/index.ts
> -      meta: { requiresAuth: true }
adjusted

2024-08-07 10:15 UTC, saeie07 commented on client/src/assets/main.css
> +.type1 {
yes, exactly.

2024-08-07 10:16 UTC, saeie07 commented on client/src/components/Navigation.vue
> +  <nav class="navigation-bar">
see comment in WhatsApp chat

2024-08-07 11:00 UTC, saeie07 commented
1. vue3 is now implemented everywhere 
2. font color writing is adapted
3. authentication - have added it as a hidden line so we can just activate it once we're ready
4. Navigation: I have left it because it's easy to work with for me. Also I have added the content we had within LandingVue in the About just to not delete anything. 

I think all change requests are good for now? or is there anything else ? :)

2024-08-07 16:21 UTC, danielamormocea commented on client/src/assets/base.css
> +    color: var(--Font-color);
This also needs to be lower case now, I think.

2024-08-07 16:28 UTC, danielamormocea approved these changes

2024-08-08 11:06 UTC, merged